/** Bundled offline horror media — served from /public/media/horror */

export const HORROR_MEDIA_BASE = '/media/horror';

export function horrorPath(segment) {
  return `${HORROR_MEDIA_BASE}${segment}`;
}

const img = (file) => horrorPath(`/images/${file}`);
const aud = (file) => horrorPath(`/audio/${file}`);

/** Core horror images — bundled SVG, work offline */
export const HORROR_IMAGES = {
  littleGirl: img('little-girl.svg'),
  shadowFigure: img('shadow-figure.svg'),
  womanInWhite: img('woman-in-white.svg'),
  hoodedWatcher: img('hooded-watcher.svg'),
  diaryPage: img('diary-page.svg'),
  abandonedSwing: img('abandoned-swing.svg'),
  blackLantern: img('black-lantern.svg'),
  deadTree: img('dead-tree.svg'),
};

/** Bundled WAV audio — generated by scripts/generateHorrorAudio.js */
export const HORROR_AUDIO = {
  childLaughter: aud('child-laughter.wav'),
  whisperingVoices: aud('whispering-voices.wav'),
  windGusts: aud('wind-gusts.wav'),
  footsteps: aud('footsteps.wav'),
  musicBox: aud('music-box.wav'),
  radioStatic: aud('radio-static.wav'),
  swingCreak: aud('swing-creak.wav'),
  heartbeat: aud('heartbeat.wav'),
  scream: aud('scream.wav'),
};

export function resolveHorrorAssetUrl(asset) {
  if (!asset) return '';
  return (
    asset.assetUrl ||
    asset.audioUrl ||
    asset.previewUrl ||
    asset.publicUrl ||
    ''
  );
}

export function libraryAssetForInsert(asset) {
  if (!asset) return asset;
  const base = {
    ...asset,
    publicUrl: resolveHorrorAssetUrl(asset),
    assetUrl: asset.assetUrl || asset.previewUrl || '',
    audioUrl: asset.audioUrl || '',
    previewUrl: asset.previewUrl || asset.assetUrl || asset.icon,
    offline: asset.offline !== false,
    source: asset.source || 'library',
  };
  return base;
}
