import { normalizeAdventure, normalizeReward } from '../seed';
import { normalizeClaimMethod } from '../claimSystem';

export function rowToAdventure(row, clues = []) {
  const sortedClues = [...clues].sort((a, b) => a.sort_order - b.sort_order);
  return normalizeAdventure({
    id: row.id,
    title: row.title,
    location: row.location || '',
    story: row.story || '',
    sponsor: row.sponsor_name || '',
    sponsorInfo: {
      name: row.sponsor_name || '',
      logoUrl: row.sponsor_logo_url || '',
      website: row.sponsor_website || '',
    },
    distance: row.distance || '',
    prize: row.prize || '',
    status: row.status,
    difficulty: row.difficulty ?? 3,
    claimCode: row.claim_code,
    claimMethod: row.claim_method,
    qrClaimValue: row.qr_claim_value || '',
    physicalMedallionCode: row.physical_medallion_code || '',
    hintAfterTap: row.hint_after_tap || '',
    finderSearchRadiusM: row.finder_search_radius_m ?? 200,
    finderCaptureBaseM: row.finder_capture_base_m ?? 25,
    collectionId: row.collection_id || null,
    collectionName: row.collection_name || '',
    collectionBadge: row.collection_badge || '',
    collectionRewardCoins: row.collection_reward_coins ?? 0,
    collectionRewardMedallion: row.collection_reward_medallion || '',
    collectionIds: row.collection_ids || [],
    isFounderHunt: Boolean(row.is_founder_hunt),
    city: row.city || '',
    state: row.state || '',
    region: row.region || 'Kansas',
    estimatedMinutes: row.estimated_minutes ?? 25,
    milesEstimate: row.miles_estimate != null ? Number(row.miles_estimate) : null,
    playersCompleted: row.players_completed ?? 0,
    firstFinderName: row.first_finder_name || '',
    tier: row.tier || 'standard',
    premiumCoinCost: row.premium_coin_cost ?? 250,
    creatorProfileId: row.creator_profile_id || null,
    sponsorVerified: Boolean(row.sponsor_verified),
    avgRating: row.avg_rating != null ? Number(row.avg_rating) : 4.8,
    reviewCount: row.review_count ?? 0,
    couponQuantity: row.coupon_quantity ?? null,
    couponTerms: row.coupon_terms || '',
    couponExpirationDays: row.coupon_expiration_days ?? 7,
    rewardCoins: row.reward_coins ?? 0,
    potEntries: row.pot_entries ?? 0,
    bonusFinds: row.bonus_finds || [],
    finalRewards: (row.final_rewards || []).map((r) => ({
      ...r,
      desc: r.desc ?? r.description,
    })),
    clues: sortedClues.map((c) => ({
      id: c.id,
      title: c.title,
      text: c.text,
      latitude: c.latitude,
      longitude: c.longitude,
      radiusMeters: c.radius_meters,
      bonusRewardText: c.bonus_reward_text || '',
    })),
    creatorId: row.creator_id,
    playMode: row.play_mode || 'both',
    heatScore: row.heat_score ?? 0,
    heatCategory: row.heat_category || 'trending',
    finderMode: row.finder_mode || 'finder',
    arAssetType: row.ar_asset_type || 'ghost_lantern',
    isLegendaryHunt: Boolean(row.is_legendary_hunt),
    legendaryType: row.legendary_type || null,
    cashPrizePool: row.cash_prize_pool != null ? Number(row.cash_prize_pool) : 0,
    cashPayouts: row.cash_payouts || { first: 0.6, second: 0.3, random: 0.1 },
    isSponsoredDrop: Boolean(row.is_sponsored_drop),
    sponsoredDropId: row.sponsored_drop_id || null,
    storefrontPrice: row.storefront_price != null ? Number(row.storefront_price) : null,
    endRule: row.end_rule || 'no_end_date',
    endsAt: row.ends_at || null,
    endsAfterTotalCompletions: row.ends_after_total_completions ?? null,
    totalCompletions: row.total_completions ?? row.players_completed ?? 0,
    rewardsPaused: Boolean(row.rewards_paused),
    manuallyEnded: Boolean(row.manually_ended),
    reopenedAt: row.reopened_at || null,
  });
}

export function adventureToRow(adventure, creatorId) {
  const sponsor = adventure.sponsorInfo || { name: adventure.sponsor || '' };
  return {
    id: adventure.id,
    creator_id: creatorId || adventure.creatorId || null,
    title: adventure.title,
    location: adventure.location,
    story: adventure.story,
    sponsor_name: sponsor.name,
    sponsor_logo_url: sponsor.logoUrl || '',
    sponsor_website: sponsor.website || '',
    distance: adventure.distance,
    prize: adventure.prize,
    status: adventure.status,
    difficulty: adventure.difficulty,
    claim_code: adventure.claimCode,
    claim_method: normalizeClaimMethod(adventure.claimMethod),
    qr_claim_value: adventure.qrClaimValue || '',
    physical_medallion_code: adventure.physicalMedallionCode || '',
    hint_after_tap: adventure.hintAfterTap || '',
    finder_search_radius_m: adventure.finderSearchRadiusM ?? 200,
    finder_capture_base_m: adventure.finderCaptureBaseM ?? 25,
    collection_id: adventure.collectionId || null,
    collection_name: adventure.collectionName || null,
    collection_badge: adventure.collectionBadge || null,
    collection_reward_coins: adventure.collectionRewardCoins ?? 0,
    collection_reward_medallion: adventure.collectionRewardMedallion || null,
    collection_ids: adventure.collectionIds?.length ? adventure.collectionIds : [],
    is_founder_hunt: Boolean(adventure.isFounderHunt),
    city: adventure.city || null,
    state: adventure.state || null,
    region: adventure.region || 'Kansas',
    estimated_minutes: adventure.estimatedMinutes ?? 25,
    miles_estimate: adventure.milesEstimate ?? null,
    players_completed: adventure.playersCompleted ?? 0,
    first_finder_name: adventure.firstFinderName || null,
    tier: adventure.tier || 'standard',
    premium_coin_cost: adventure.premiumCoinCost ?? 250,
    creator_profile_id: adventure.creatorProfileId || null,
    sponsor_verified: Boolean(adventure.sponsorVerified || adventure.sponsorInfo?.verified),
    avg_rating: adventure.avgRating ?? null,
    review_count: adventure.reviewCount ?? 0,
    coupon_quantity: adventure.couponQuantity ?? null,
    coupon_terms: adventure.couponTerms || null,
    coupon_expiration_days: adventure.couponExpirationDays ?? 7,
    reward_coins: adventure.rewardCoins ?? 0,
    pot_entries: adventure.potEntries ?? 0,
    bonus_finds: adventure.bonusFinds || [],
    final_rewards: adventure.finalRewards || [],
    play_mode: adventure.playMode || 'both',
    heat_score: adventure.heatScore ?? 0,
    heat_category: adventure.heatCategory || 'trending',
    finder_mode: adventure.finderMode || 'finder',
    ar_asset_type: adventure.arAssetType || 'ghost_lantern',
    is_legendary_hunt: Boolean(adventure.isLegendaryHunt),
    legendary_type: adventure.legendaryType || null,
    cash_prize_pool: adventure.cashPrizePool ?? 0,
    cash_payouts: adventure.cashPayouts || { first: 0.6, second: 0.3, random: 0.1 },
    is_sponsored_drop: Boolean(adventure.isSponsoredDrop),
    sponsored_drop_id: adventure.sponsoredDropId || null,
    storefront_price: adventure.storefrontPrice ?? null,
    end_rule: adventure.endRule || 'no_end_date',
    ends_at: adventure.endsAt || null,
    ends_after_total_completions: adventure.endsAfterTotalCompletions ?? null,
    total_completions: adventure.totalCompletions ?? adventure.playersCompleted ?? 0,
    rewards_paused: Boolean(adventure.rewardsPaused),
    manually_ended: Boolean(adventure.manuallyEnded),
    reopened_at: adventure.reopenedAt || null,
  };
}

export function cluesToRows(adventure) {
  return (adventure.clues || []).map((clue, index) => ({
    id: clue.id,
    adventure_id: adventure.id,
    sort_order: index,
    title: clue.title,
    text: clue.text,
    latitude: clue.latitude,
    longitude: clue.longitude,
    radius_meters: clue.radiusMeters ?? 500,
    bonus_reward_text: clue.bonusRewardText || null,
  }));
}

export function rewardsToRows(adventure) {
  return (adventure.finalRewards || []).map((reward, index) => ({
    id: reward.id || `${adventure.id}-reward-${index}`,
    adventure_id: adventure.id,
    sort_order: index,
    type: reward.type,
    icon: reward.icon,
    title: reward.title,
    description: reward.desc ?? reward.description ?? '',
    value_label: reward.valueLabel || '',
    redemption_instructions: reward.redemptionInstructions || '',
    expiration_days: reward.expirationDays ?? 0,
    quantity_limit: reward.quantityLimit ?? null,
    claimed_count: reward.claimedCount ?? 0,
    reward_window_start: reward.rewardWindowStart || null,
    reward_window_end: reward.rewardWindowEnd || null,
    reward_policy: reward.rewardPolicy || 'continue_badge_coins_only',
    rewards_paused: Boolean(reward.rewardsPaused),
    backup_reward: reward.backupReward || null,
  }));
}

export function rowToUserReward(row) {
  return normalizeReward({
    id: row.id,
    type: row.type,
    icon: row.icon,
    title: row.title,
    desc: row.description,
    valueLabel: row.value_label,
    redemptionInstructions: row.redemption_instructions,
    adventureId: row.adventure_id,
    adventureTitle: row.adventure_title,
    sponsorName: row.sponsor_name,
    sponsorLogoUrl: row.sponsor_logo_url,
    sponsorWebsite: row.sponsor_website,
    status: row.status,
    claimedAt: row.claimed_at,
    redeemedAt: row.redeemed_at,
    expiresAt: row.expires_at,
  });
}

export function userRewardToRow(reward, userId) {
  return {
    id: reward.id,
    user_id: userId,
    adventure_id: reward.adventureId,
    type: reward.type,
    icon: reward.icon,
    title: reward.title,
    description: reward.desc,
    value_label: reward.valueLabel,
    redemption_instructions: reward.redemptionInstructions,
    adventure_title: reward.adventureTitle,
    sponsor_name: reward.sponsorName,
    sponsor_logo_url: reward.sponsorLogoUrl,
    sponsor_website: reward.sponsorWebsite,
    status: reward.status,
    claimed_at: reward.claimedAt,
    redeemed_at: reward.redeemedAt,
    expires_at: reward.expiresAt,
  };
}

export function rowToClaimHistory(row) {
  return {
    id: row.id,
    kind: row.kind,
    adventureId: row.adventure_id,
    adventureName: row.adventure_name,
    rewardName: row.reward_name,
    type: row.type,
    status: row.status,
    claimedAt: row.claimed_at,
    redeemedAt: row.redeemed_at,
    shareText: row.share_text,
    sponsorName: row.sponsor_name,
    sponsorLogoUrl: row.sponsor_logo_url,
    sponsorWebsite: row.sponsor_website,
    verified: row.verified,
    completedAt: row.claimed_at,
  };
}

export function claimHistoryToRow(entry, userId) {
  return {
    id: entry.id,
    user_id: userId,
    adventure_id: entry.adventureId || null,
    kind: entry.kind || 'reward',
    adventure_name: entry.adventureName,
    reward_name: entry.rewardName,
    type: entry.type,
    status: entry.status,
    claimed_at: entry.claimedAt || entry.completedAt,
    redeemed_at: entry.redeemedAt,
    share_text: entry.shareText,
    sponsor_name: entry.sponsorName,
    sponsor_logo_url: entry.sponsorLogoUrl,
    sponsor_website: entry.sponsorWebsite,
    verified: entry.verified ?? false,
  };
}
